export const REVIEWS_DATA = [
  {
    id: 'rev-1',
    name: 'Adeel Ahmad',
    role: 'Porsche 911 GT3',
    service: 'Steam Wash & Detailing',
    rating: 5,
    source: 'App Store',
    comment: 'Unbelievable steam wash quality at my doorstep. The detailer took immense care of the paintwork and ceramic finish. Zero water spots, spotless interior.',
  },
  {
    id: 'rev-2',
    name: 'Sarah Al-Mansoor',
    role: 'Range Rover SV',
    service: 'Doorstep Battery Replacement',
    rating: 5,
    source: 'Google Play',
    comment: 'Dead battery in my office basement at 7 PM. Booked on the STYLEIN app and the mobile technician arrived in 18 minutes with an OEM AGM battery. Saved my evening!',
  },
  {
    id: 'rev-3',
    name: 'Marcus Vance',
    role: 'BMW M4 Competition',
    service: 'Synthetic Oil Change',
    rating: 5,
    source: 'App Store',
    comment: 'Complete Castrol Edge synthetic oil and filter replacement done right in my villa driveway. Transparent digital inspection report sent directly to my phone.',
  },
  {
    id: 'rev-4',
    name: 'Tariq Hashmi',
    role: 'Mercedes-AMG G63',
    service: '9H Ceramic Shield',
    rating: 5,
    source: 'App Store',
    comment: 'Top-tier ceramic coating service. The car has insane hydrophobic gloss and deep reflections. The technicians are true automotive perfectionists.',
  },
  {
    id: 'rev-5',
    name: 'Elena Rostova',
    role: 'Audi RS6 Avant',
    service: '24/7 Roadside Rescue',
    rating: 5,
    source: 'Google Play',
    comment: 'Had a puncture on the highway. Hit the red Rescue button and live tracked their van. Fast, professional, and had me back on the road in no time.',
  },
];
