export const DEFAULT_SEO_BY_KEY = {
  home: {
    metaTitle: 'STYLEIN | Premium On-Demand Car Services & Mobile Auto Care',
    metaDescription: 'The all-in-one app for your car. Premium car wash, tyre change, detailing, battery replacement & roadside assistance delivered to your doorstep in UAE.',
    metaKeywords: 'car wash dubai, mobile car detailing uae, tyre replacement, battery jumpstart, doorstep car maintenance, luxury auto care',
    ogTitle: 'STYLEIN | Premium On-Demand Car Services & Mobile Auto Care',
    ogDescription: 'The all-in-one app for your car. Certified automotive care delivered to your doorstep in UAE.',
    ogImage: 'https://storage.googleapis.com/stylein_bucket/Home_services/Car_Wash.webp',
  },
  services: {
    metaTitle: 'Our Automotive Services | Mobile Car Care & Detailing | STYLEIN',
    metaDescription: 'Explore STYLEIN\'s comprehensive mobile car care services in Dubai & UAE - from exterior foam wash to interior detailing, ceramic coating, PPF, and battery replacement.',
    metaKeywords: 'car detailing dubai, ceramic coating, car wash at doorstep, steam wash uae, luxury car service, auto detailing packages',
    ogTitle: 'Automotive Services | STYLEIN Mobile Care',
    ogDescription: 'Comprehensive doorstep automotive solutions for luxury, exotic, and daily cars in UAE.',
    ogImage: 'https://storage.googleapis.com/stylein_bucket/Home_services/Car_Wash.webp',
  },
  'service-detail': {
    metaTitle: 'Service Details & Pricing | STYLEIN Doorstep Car Care',
    metaDescription: 'Detailed breakdown of services, pricing, steps, and certified equipment used by STYLEIN mobile workshop units across the UAE.',
    metaKeywords: 'car care packages, service pricing dubai, mobile car wash booking, certified auto service',
    ogTitle: 'Service Details | STYLEIN',
    ogDescription: 'Book certified on-demand automotive services directly to your location.',
    ogImage: 'https://storage.googleapis.com/stylein_bucket/Home_services/Car_Wash.webp',
  },
  rescue: {
    metaTitle: '24/7 Emergency Roadside Assistance & Rescue | STYLEIN UAE',
    metaDescription: 'Rapid 20-30 min emergency rescue in Dubai & UAE. Flat tyre change, dead battery jumpstart & replacement, emergency tyre pressure on-site.',
    metaKeywords: 'emergency roadside assistance dubai, flat tyre repair uae, battery jump start on-demand, car breakdown rescue',
    ogTitle: '24/7 Roadside Rescue | STYLEIN UAE',
    ogDescription: 'Rapid response emergency assistance reaching your GPS location in 20-30 mins.',
    ogImage: 'https://storage.googleapis.com/stylein_bucket/Home_services/Rescue.webp',
  },
  brands: {
    metaTitle: 'Luxury & Exotic Car Brands We Service | STYLEIN UAE',
    metaDescription: 'Specialized doorstep car care for Porsche, Mercedes-Benz, BMW, Audi, Ferrari, Lamborghini, Rolls-Royce, Tesla, and more using OEM-approved tools.',
    metaKeywords: 'luxury car service dubai, exotic car detailing, porsche service uae, mercedes wash, supercar maintenance',
    ogTitle: 'Luxury Brands Serviced | STYLEIN',
    ogDescription: 'Trusted care for the world\'s most prestigious automotive marques.',
    ogImage: 'https://storage.googleapis.com/stylein_bucket/Home_services/Car_Wash.webp',
  },
  about: {
    metaTitle: 'About STYLEIN | Redefining Automotive Convenience in UAE',
    metaDescription: 'Learn about STYLEIN\'s mission to revolutionize automotive car care with certified technicians, eco-friendly products, and fully equipped mobile workshops.',
    metaKeywords: 'about stylein, automotive startup dubai, mobile car workshop uae, car care innovators',
    ogTitle: 'About STYLEIN | Revolutionizing Car Care',
    ogDescription: 'Discover how STYLEIN brings the workshop directly to you.',
    ogImage: 'https://storage.googleapis.com/stylein_bucket/Home_services/Car_Wash.webp',
  },
  contact: {
    metaTitle: 'Contact STYLEIN | Book Your Car Service Today',
    metaDescription: 'Get in touch with STYLEIN customer support. Call, WhatsApp, or email our team for bookings, corporate fleets, and inquiries in UAE.',
    metaKeywords: 'contact stylein, car service helpline dubai, stylein whatsapp, customer support uae',
    ogTitle: 'Contact STYLEIN Customer Care',
    ogDescription: 'We\'re here to assist with bookings, corporate fleets, and inquiries.',
    ogImage: 'https://storage.googleapis.com/stylein_bucket/Home_services/Car_Wash.webp',
  },
  faqs: {
    metaTitle: 'FAQs | Answers About STYLEIN Doorstep Car Services',
    metaDescription: 'Find answers to common questions about booking, pricing, service timings, technician certifications, coverage areas across Dubai and UAE.',
    metaKeywords: 'stylein faqs, car service questions, mobile car wash prices dubai, doorstep booking help',
    ogTitle: 'Frequently Asked Questions | STYLEIN',
    ogDescription: 'Everything you need to know about STYLEIN automotive services.',
    ogImage: 'https://storage.googleapis.com/stylein_bucket/Home_services/Car_Wash.webp',
  },
  legal: {
    metaTitle: 'Terms of Service & Privacy Policy | STYLEIN UAE',
    metaDescription: 'Read our terms and conditions, privacy policy, user data handling, and service guarantees for STYLEIN automotive applications and services.',
    metaKeywords: 'terms and conditions, privacy policy, stylein legal terms, user agreement dubai',
    ogTitle: 'Terms & Privacy Policy | STYLEIN',
    ogDescription: 'Legal policies, user guarantees, and data protection terms.',
    ogImage: 'https://storage.googleapis.com/stylein_bucket/Home_services/Car_Wash.webp',
  },
};

export function generateSchemaJsonLd(pageKey, title, description, url) {
  const baseSchema = {
    '@context': 'https://schema.org',
    '@graph': [
      {
        '@type': 'AutoRepair',
        '@id': 'https://www.styleincar.com/#autorepair',
        name: 'STYLEIN | Doorstep Car Care & Roadside Assistance',
        alternateName: 'STYLEIN Car Services LLC',
        url: 'https://www.styleincar.com/',
        logo: 'https://www.styleincar.com/favicon.webp',
        image: 'https://storage.googleapis.com/stylein_bucket/Home_services/Car_Wash.webp',
        description: description || 'On-demand doorstep automotive care in UAE. Certified mobile car wash, tyre replacement, oil change, battery service, and 24/7 roadside emergency rescue.',
        priceRange: '$$',
        telephone: '+971558120570',
        address: {
          '@type': 'PostalAddress',
          addressLocality: 'Dubai',
          addressCountry: 'AE',
        },
        areaServed: [
          { '@type': 'City', name: 'Dubai' },
          { '@type': 'City', name: 'Abu Dhabi' },
          { '@type': 'City', name: 'Sharjah' },
          { '@type': 'City', name: 'Ajman' },
          { '@type': 'Country', name: 'United Arab Emirates' },
        ],
        openingHoursSpecification: {
          '@type': 'OpeningHoursSpecification',
          dayOfWeek: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'],
          opens: '00:00',
          closes: '23:59',
        },
        sameAs: [
          'https://www.instagram.com/styleincar',
          'https://www.facebook.com/profile.php?id=61587131289144',
          'https://www.tiktok.com/discover/stylein-car-services-llc-ajman-uae',
          'https://www.linkedin.com/in/stylein-car-6a65b93b4/',
          'https://x.com/StyleinCar',
          'https://www.youtube.com/@StyleinCar',
          'https://in.pinterest.com/styleincaar/styleincar-premium-car-detailing-mods/',
        ],
      },
      {
        '@type': 'WebPage',
        '@id': `${url}#webpage`,
        url,
        name: title,
        description,
        isPartOf: {
          '@type': 'WebSite',
          '@id': 'https://www.styleincar.com/#website',
          url: 'https://www.styleincar.com/',
          name: 'STYLEIN',
        },
      },
    ],
  };

  return baseSchema;
}
