export const SERVICES_SECTION_DATA = [
  {
    id: 'car-wash',
    label: 'Car Wash',
    iconName: 'Sparkles',
    title: 'Spotless shine delivered to your door.',
    description: 'Premium eco-friendly car wash at your location. Interior deep clean, exterior polish & ceramic finish — without leaving home.',
    cta: 'Discover car wash',
    href: '#car-wash',
    image: 'https://images.unsplash.com/photo-1520340356584-f9917d1eea6f?w=600&q=80',
  },
  {
    id: 'battery',
    label: 'Battery',
    iconName: 'Zap',
    title: 'Stay charged — battery swap in minutes.',
    description: 'Unsure which battery you need? Our specialist technicians will test, diagnose & replace your car battery on the spot.',
    cta: 'Discover battery change',
    href: '#battery',
    image: 'https://images.unsplash.com/photo-1619642751034-765dfdf7c58e?w=600&q=80',
  },
  {
    id: 'tyres',
    label: 'Tyres',
    iconName: 'Disc',
    title: "Worn treads? We'll upgrade them today.",
    description: 'Skip the garage. Mobile tyre fitting, balancing & alignment delivered to your doorstep with premium brand options.',
    cta: 'Discover tyre change',
    href: '#tyres',
    image: 'https://images.unsplash.com/photo-1578844251758-2f71da64c96f?w=600&q=80',
  },
  {
    id: 'engine-oil',
    label: 'Engine Oil',
    iconName: 'Gauge',
    title: 'Engine oil with free 10-point check.',
    description: 'Mobile oil change, free 10-point check & original filter replacement. Your car deserves the best.',
    cta: 'Discover engine oil',
    href: '#engine-oil',
    image: 'https://images.unsplash.com/photo-1487754180451-c456f719a1fc?w=600&q=80',
  },
  {
    id: 'glass-coating',
    label: 'Glass Coating',
    iconName: 'ShieldCheck',
    title: 'Shield your paint with ceramic armour.',
    description: 'Professional ceramic coating & paint protection film applied at your location. Long-lasting showroom finish guaranteed.',
    cta: 'Discover glass coating',
    href: '#glass-coating',
    image: 'https://images.unsplash.com/photo-1507136566006-cfc505b114fc?w=600&q=80',
  },
  {
    id: 'car-inspection',
    label: 'Car Inspection',
    iconName: 'CheckCircle2',
    title: 'Full 50-point diagnostic at your door.',
    description: 'Comprehensive vehicle inspection covering engine, brakes, suspension & electronics — detailed digital report included.',
    cta: 'Discover inspection',
    href: '#car-inspection',
    image: 'https://images.unsplash.com/photo-1530046339160-ce3e530c7d2f?w=600&q=80',
  },
  {
    id: 'rescue',
    label: 'Rescue',
    iconName: 'LifeBuoy',
    title: 'Stuck at the roadside? Help is coming.',
    description: "Ran out of fuel? Puncture? Battery dead? STYLEIN's rapid rescue team reaches you in minutes, 24/7.",
    cta: 'Get rescued now',
    ctaSecondary: 'Learn more',
    href: '#rescue',
    isRescue: true,
    image: 'https://images.unsplash.com/photo-1549317661-bd32c8ce0abb?w=600&q=80',
  },
];
